#logging.level:
#  root: WARN

spring:
  data.rest.base-path: /api
  test.database.replace: NONE
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER:}
    password: ${DB_PASS:}
    tomcat.max-active: ${DB_MAX_ACTIVE:100}
  jpa:
    properties.hibernate:
      show_sql: false

#spring.datasource.driverClassName: org.postgresql.Driver
#spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto: validate
#spring.jpa.properties.hibernate.jdbc.time_zone: UTC
